server {
    listen 8080;
    server_name localhost;

    client_max_body_size 100M;

    root ./tester/webserv_tester/www;
    index index.html;
    autoindex on;

    error_page 404 /error404.html;

    location / {
        root ./tester/webserv_tester/www;
        index index.html;
        allow_methods GET HEAD POST PUT DELETE;
    }

    location /2/ {
        root ./tester/webserv_tester/www;
        index second.html;
    }

    location /virtual/ {
        root ./tester/webserv_tester/www;
        autoindex off;
    }

    location /post {
        root ./tester/webserv_tester/www;
        allow_methods GET POST PUT DELETE;
        upload_store ./tester/webserv_tester/www/tmp;
        client_max_body_size 1024;
        cgi_extension .cgi;
        cgi_path ./tester/webserv_tester/cgi-bin/print_cgi;
    }

    location /put {
        root ./tester/webserv_tester/www;
        allow_methods GET PUT;
    }

    location /index/ {
        root ./tester/webserv_tester/www;
        autoindex on;
    }

    location /protected {
        root ./tester/webserv_tester/www/protected;
        cgi_extension .cgi;
        cgi_path ./tester/webserv_tester/cgi-bin/print_cgi;
    }

    location /cgi {
        root ./tester/webserv_tester/www;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        allow_methods GET POST;
    }
}

server {
    listen 8081;
    server_name localhost;

    root ./tester/webserv_tester/www;
    index second.html;
}

server {
    listen 8080;
    server_name google.com;

    root ./tester/webserv_tester/www;
    index google.html;

    location /auto {
        root ./tester/webserv_tester/www/auto;
        autoindex on;
    }
}